---
title: "hw01_gapminder"
author: "Matt Madsen"
date: "`r format(Sys.Date())`"
output: github_document
---

```{r}
install.packages(ggplot2)
install.packages(gapminder)
```


```{r include = FALSE}
library(ggplot2)
library(gapminder)
```

```{r include = FALSE}
library(gapminder)
```
#Some Facts about the World

#####Tail of the data
```{r}
tail(gapminder)
```

#####Summary of the data

```{r echo = FALSE}
summary(gapminder)
```

#####Has Life Expectancy Increased? 

```{r echo = FALSE}
plot(lifeExp ~ year, gapminder)
```

#####How is Wealth Divided?

```{r echo = FALSE}
hist(gapminder$gdpPercap)
```

##How About Canada

Well it looks like we are living longer with the years.... 

```{r echo = FALSE}
p <- ggplot(subset(gapminder, country == 'Canada'), aes (x = year, y = lifeExp)) 

p + geom_point() + geom_smooth(lwd = 1, se = FALSE, method = "lm")
```

And getting wealthier...Hot Damn... 

```{r echo = FALSE}
q <- ggplot(subset(gapminder, country == 'Canada'),  aes (x = year, y = gdpPercap))

q + geom_point() + geom_smooth(lwd = 1, se = FALSE, method = "lm")
```













