---
title: "BIOL351_lab5"
author: "Matt Madsen"
date: "October 22, 2016"
output: github_document
---
```{r}
library(tidyverse)
library(ggplot2)
library(viridis)
library(knitr)
```

```{r}

dat = read_csv("plants.csv")

head(dat)

light <- dat %>% 
  select(treatment, avg_nit_red, group) %>% 
  filter(group =="Light")


```

```{r, fig.width = 8, fig.height = 10}

colors1= viridis(6)

labels1 <- c("Dark                         .",              "Light                        .",              "Light + CYK                  .",              "No NO3                   .",              "24 Hrs. NO3                 .",              "24 Hrs. NO3 + CHEX")
p <- ggplot(dat, aes(treatment, avg_nit_red)) +
  geom_bar(stat = 'identity',  fill= colors1 )  

p <- p + labs(x = NULL,  y = " Average Nitrate Reductase Activity (nmol/gFW/min)")+
  theme_bw()+
  theme(axis.title.x =element_text(size=9, vjust = 0.9), axis.text.x=element_text(angle= 300, size=8, vjust = 0.75, hjust= 0.2), axis.title.y = element_text(size=9), panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank())

p <- p + scale_x_discrete(labels = labels1)  

 

p

ggsave("biol351_lab5_plot2.jpeg", width = 12, height=12, units = "cm")
```

```{r results = 'asis'}

knitr::kable(dat)
```

